// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: builtin/builtin.proto

package builtin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiContext int32

const (
	ApiContext_ALL   ApiContext = 0
	ApiContext_BZL   ApiContext = 1
	ApiContext_BUILD ApiContext = 2
)

// Enum value maps for ApiContext.
var (
	ApiContext_name = map[int32]string{
		0: "ALL",
		1: "BZL",
		2: "BUILD",
	}
	ApiContext_value = map[string]int32{
		"ALL":   0,
		"BZL":   1,
		"BUILD": 2,
	}
)

func (x ApiContext) Enum() *ApiContext {
	p := new(ApiContext)
	*p = x
	return p
}

func (x ApiContext) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiContext) Descriptor() protoreflect.EnumDescriptor {
	return file_builtin_builtin_proto_enumTypes[0].Descriptor()
}

func (ApiContext) Type() protoreflect.EnumType {
	return &file_builtin_builtin_proto_enumTypes[0]
}

func (x ApiContext) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiContext.Descriptor instead.
func (ApiContext) EnumDescriptor() ([]byte, []int) {
	return file_builtin_builtin_proto_rawDescGZIP(), []int{0}
}

type Builtins struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          []*Type                `protobuf:"bytes,1,rep,name=type,proto3" json:"type,omitempty"`
	Global        []*Value               `protobuf:"bytes,2,rep,name=global,proto3" json:"global,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Builtins) Reset() {
	*x = Builtins{}
	mi := &file_builtin_builtin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Builtins) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Builtins) ProtoMessage() {}

func (x *Builtins) ProtoReflect() protoreflect.Message {
	mi := &file_builtin_builtin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Builtins.ProtoReflect.Descriptor instead.
func (*Builtins) Descriptor() ([]byte, []int) {
	return file_builtin_builtin_proto_rawDescGZIP(), []int{0}
}

func (x *Builtins) GetType() []*Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Builtins) GetGlobal() []*Value {
	if x != nil {
		return x.Global
	}
	return nil
}

type Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Field         []*Value               `protobuf:"bytes,2,rep,name=field,proto3" json:"field,omitempty"`
	Doc           string                 `protobuf:"bytes,3,opt,name=doc,proto3" json:"doc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_builtin_builtin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_builtin_builtin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_builtin_builtin_proto_rawDescGZIP(), []int{1}
}

func (x *Type) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Type) GetField() []*Value {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *Type) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Callable      *Callable              `protobuf:"bytes,3,opt,name=callable,proto3" json:"callable,omitempty"`
	Doc           string                 `protobuf:"bytes,4,opt,name=doc,proto3" json:"doc,omitempty"`
	ApiContext    ApiContext             `protobuf:"varint,5,opt,name=api_context,json=apiContext,proto3,enum=builtin.ApiContext" json:"api_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_builtin_builtin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_builtin_builtin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_builtin_builtin_proto_rawDescGZIP(), []int{2}
}

func (x *Value) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Value) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Value) GetCallable() *Callable {
	if x != nil {
		return x.Callable
	}
	return nil
}

func (x *Value) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (x *Value) GetApiContext() ApiContext {
	if x != nil {
		return x.ApiContext
	}
	return ApiContext_ALL
}

type Callable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Param         []*Param               `protobuf:"bytes,1,rep,name=param,proto3" json:"param,omitempty"`
	ReturnType    string                 `protobuf:"bytes,2,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Callable) Reset() {
	*x = Callable{}
	mi := &file_builtin_builtin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Callable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Callable) ProtoMessage() {}

func (x *Callable) ProtoReflect() protoreflect.Message {
	mi := &file_builtin_builtin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Callable.ProtoReflect.Descriptor instead.
func (*Callable) Descriptor() ([]byte, []int) {
	return file_builtin_builtin_proto_rawDescGZIP(), []int{3}
}

func (x *Callable) GetParam() []*Param {
	if x != nil {
		return x.Param
	}
	return nil
}

func (x *Callable) GetReturnType() string {
	if x != nil {
		return x.ReturnType
	}
	return ""
}

type Param struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Doc           string                 `protobuf:"bytes,3,opt,name=doc,proto3" json:"doc,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	IsMandatory   bool                   `protobuf:"varint,5,opt,name=is_mandatory,json=isMandatory,proto3" json:"is_mandatory,omitempty"`
	IsStarArg     bool                   `protobuf:"varint,6,opt,name=is_star_arg,json=isStarArg,proto3" json:"is_star_arg,omitempty"`
	IsStarStarArg bool                   `protobuf:"varint,7,opt,name=is_star_star_arg,json=isStarStarArg,proto3" json:"is_star_star_arg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Param) Reset() {
	*x = Param{}
	mi := &file_builtin_builtin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_builtin_builtin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_builtin_builtin_proto_rawDescGZIP(), []int{4}
}

func (x *Param) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Param) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Param) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (x *Param) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *Param) GetIsMandatory() bool {
	if x != nil {
		return x.IsMandatory
	}
	return false
}

func (x *Param) GetIsStarArg() bool {
	if x != nil {
		return x.IsStarArg
	}
	return false
}

func (x *Param) GetIsStarStarArg() bool {
	if x != nil {
		return x.IsStarStarArg
	}
	return false
}

var File_builtin_builtin_proto protoreflect.FileDescriptor

const file_builtin_builtin_proto_rawDesc = "" +
	"\n" +
	"\x15builtin/builtin.proto\x12\abuiltin\"U\n" +
	"\bBuiltins\x12!\n" +
	"\x04type\x18\x01 \x03(\v2\r.builtin.TypeR\x04type\x12&\n" +
	"\x06global\x18\x02 \x03(\v2\x0e.builtin.ValueR\x06global\"R\n" +
	"\x04Type\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12$\n" +
	"\x05field\x18\x02 \x03(\v2\x0e.builtin.ValueR\x05field\x12\x10\n" +
	"\x03doc\x18\x03 \x01(\tR\x03doc\"\xa6\x01\n" +
	"\x05Value\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12-\n" +
	"\bcallable\x18\x03 \x01(\v2\x11.builtin.CallableR\bcallable\x12\x10\n" +
	"\x03doc\x18\x04 \x01(\tR\x03doc\x124\n" +
	"\vapi_context\x18\x05 \x01(\x0e2\x13.builtin.ApiContextR\n" +
	"apiContext\"Q\n" +
	"\bCallable\x12$\n" +
	"\x05param\x18\x01 \x03(\v2\x0e.builtin.ParamR\x05param\x12\x1f\n" +
	"\vreturn_type\x18\x02 \x01(\tR\n" +
	"returnType\"\xd2\x01\n" +
	"\x05Param\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x10\n" +
	"\x03doc\x18\x03 \x01(\tR\x03doc\x12#\n" +
	"\rdefault_value\x18\x04 \x01(\tR\fdefaultValue\x12!\n" +
	"\fis_mandatory\x18\x05 \x01(\bR\visMandatory\x12\x1e\n" +
	"\vis_star_arg\x18\x06 \x01(\bR\tisStarArg\x12'\n" +
	"\x10is_star_star_arg\x18\a \x01(\bR\risStarStarArg*)\n" +
	"\n" +
	"ApiContext\x12\a\n" +
	"\x03ALL\x10\x00\x12\a\n" +
	"\x03BZL\x10\x01\x12\t\n" +
	"\x05BUILD\x10\x02Bh\n" +
	"(com.google.devtools.build.docgen.builtinB\rBuiltinProtosZ-github.com/bazel-contrib/bcr-frontend/builtinb\x06proto3"

var (
	file_builtin_builtin_proto_rawDescOnce sync.Once
	file_builtin_builtin_proto_rawDescData []byte
)

func file_builtin_builtin_proto_rawDescGZIP() []byte {
	file_builtin_builtin_proto_rawDescOnce.Do(func() {
		file_builtin_builtin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_builtin_builtin_proto_rawDesc), len(file_builtin_builtin_proto_rawDesc)))
	})
	return file_builtin_builtin_proto_rawDescData
}

var file_builtin_builtin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_builtin_builtin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_builtin_builtin_proto_goTypes = []any{
	(ApiContext)(0),  // 0: builtin.ApiContext
	(*Builtins)(nil), // 1: builtin.Builtins
	(*Type)(nil),     // 2: builtin.Type
	(*Value)(nil),    // 3: builtin.Value
	(*Callable)(nil), // 4: builtin.Callable
	(*Param)(nil),    // 5: builtin.Param
}
var file_builtin_builtin_proto_depIdxs = []int32{
	2, // 0: builtin.Builtins.type:type_name -> builtin.Type
	3, // 1: builtin.Builtins.global:type_name -> builtin.Value
	3, // 2: builtin.Type.field:type_name -> builtin.Value
	4, // 3: builtin.Value.callable:type_name -> builtin.Callable
	0, // 4: builtin.Value.api_context:type_name -> builtin.ApiContext
	5, // 5: builtin.Callable.param:type_name -> builtin.Param
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_builtin_builtin_proto_init() }
func file_builtin_builtin_proto_init() {
	if File_builtin_builtin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_builtin_builtin_proto_rawDesc), len(file_builtin_builtin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_builtin_builtin_proto_goTypes,
		DependencyIndexes: file_builtin_builtin_proto_depIdxs,
		EnumInfos:         file_builtin_builtin_proto_enumTypes,
		MessageInfos:      file_builtin_builtin_proto_msgTypes,
	}.Build()
	File_builtin_builtin_proto = out.File
	file_builtin_builtin_proto_goTypes = nil
	file_builtin_builtin_proto_depIdxs = nil
}
